language: node_js

node_js:
  - 8.11.2

# Define services.
services:
  - mysql

# Define directories cached.
cache:
  directories:
    - "node_modules"

# Define notifications per email always than build success and failure.
notifications:
  emails:
    - tiagorosadacost@gmail.com
  on_success: always
  on_failure: always 

# Define branch running travis-ci.
branchs:
  only:
    - master

# Define variables environment.
env:
  - PORT=3000
  - HOST=localhost
  - USER=root
  - PASSWORD=root
  - DATABASE=futiba_clube